# DO NOT EDIT THIS FILE!
#
# Python module guiCutThrough__POA generated by omniidl

import omniORB
omniORB.updateModule("guiCutThrough__POA")

# ** 1. Stub files contributing to this module
import guiCutThrough_idl

# ** 2. Sub-modules

# ** 3. End
