# DO NOT EDIT THIS FILE!
#
# Python module mLSNPPLink__POA generated by omniidl

import omniORB
omniORB.updateModule("mLSNPPLink__POA")

# ** 1. Stub files contributing to this module
from corba_client.IDL import mLSNPPLink_idl

# ** 2. Sub-modules

# ** 3. End
