# DO NOT EDIT THIS FILE!
#
# Python module equipment generated by omniidl

import omniORB
omniORB.updateModule("equipment")

# ** 1. Stub files contributing to this module
from corba_client.IDL import equipment_idl

# ** 2. Sub-modules

# ** 3. End
