# DO NOT EDIT THIS FILE!
#
# Python module flowDomain generated by omniidl

import omniORB
omniORB.updateModule("flowDomain")

# ** 1. Stub files contributing to this module
import flowDomain_idl

# ** 2. Sub-modules

# ** 3. End
