# DO NOT EDIT THIS FILE!
#
# Python module flowDomainFragment__POA generated by omniidl

import omniORB
omniORB.updateModule("flowDomainFragment__POA")

# ** 1. Stub files contributing to this module
import flowDomainFragment_idl

# ** 2. Sub-modules

# ** 3. End
