# DO NOT EDIT THIS FILE!
#
# Python module nmsSession__POA generated by omniidl

import omniORB
omniORB.updateModule("nmsSession__POA")

# ** 1. Stub files contributing to this module
from corba_client.IDL import nmsSession_idl

# ** 2. Sub-modules

# ** 3. End
