# DO NOT EDIT THIS FILE!
#
# Python module DsEventLogAdmin__POA generated by omniidl

import omniORB
omniORB.updateModule("DsEventLogAdmin__POA")

# ** 1. Stub files contributing to this module
import DsEventLogAdmin_idl

# ** 2. Sub-modules

# ** 3. End
