# DO NOT EDIT THIS FILE!
#
# Python module CORBA__POA generated by omniidl

import omniORB
omniORB.updateModule("CORBA__POA")

# ** 1. Stub files contributing to this module
import orb_idl

# ** 2. Sub-modules

# ** 3. End
