# DO NOT EDIT THIS FILE!
#
# Python module CORBA generated by omniidl

import omniORB
omniORB.updateModule("CORBA")

# ** 1. Stub files contributing to this module
from corba_client.IDL.OMGidl import orb_idl

# ** 2. Sub-modules

# ** 3. End
