# DO NOT EDIT THIS FILE!
#
# Python module DsLogAdmin__POA generated by omniidl

import omniORB
omniORB.updateModule("DsLogAdmin__POA")

# ** 1. Stub files contributing to this module
import DsLogAdmin_idl

# ** 2. Sub-modules

# ** 3. End
