# DO NOT EDIT THIS FILE!
#
# Python module aSAP generated by omniidl

import omniORB
omniORB.updateModule("aSAP")

# ** 1. Stub files contributing to this module
import aSAP_idl

# ** 2. Sub-modules

# ** 3. End
