# DO NOT EDIT THIS FILE!
#
# Python module flowDomainFragment generated by omniidl

import omniORB
omniORB.updateModule("flowDomainFragment")

# ** 1. Stub files contributing to this module
import flowDomainFragment_idl

# ** 2. Sub-modules

# ** 3. End
