# DO NOT EDIT THIS FILE!
#
# Python module mtnmVersion__POA generated by omniidl

import omniORB
omniORB.updateModule("mtnmVersion__POA")

# ** 1. Stub files contributing to this module

# ** 2. Sub-modules

# ** 3. End
