# DO NOT EDIT THIS FILE!
#
# Python module callSNC__POA generated by omniidl

import omniORB
omniORB.updateModule("callSNC__POA")

# ** 1. Stub files contributing to this module
import callSNC_idl

# ** 2. Sub-modules

# ** 3. End
