# DO NOT EDIT THIS FILE!
#
# Python module softwareAndDataManager__POA generated by omniidl

import omniORB
omniORB.updateModule("softwareAndDataManager__POA")

# ** 1. Stub files contributing to this module
from corba_client.IDL import softwareAndDataManager_idl

# ** 2. Sub-modules

# ** 3. End
