# DO NOT EDIT THIS FILE!
#
# Python module DsEventLogAdmin generated by omniidl

import omniORB
omniORB.updateModule("DsEventLogAdmin")

# ** 1. Stub files contributing to this module
import DsEventLogAdmin_idl

# ** 2. Sub-modules

# ** 3. End
