# Python stubs generated by omniidl from maintenanceOps.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


# #include "globaldefs.idl"
import globaldefs_idl
_0_globaldefs = omniORB.openModule("globaldefs")
_0_globaldefs__POA = omniORB.openModule("globaldefs__POA")

# #include "common.idl"
import common_idl
_0_common = omniORB.openModule("common")
_0_common__POA = omniORB.openModule("common__POA")

# #include "transmissionParameters.idl"
import transmissionParameters_idl
_0_transmissionParameters = omniORB.openModule("transmissionParameters")
_0_transmissionParameters__POA = omniORB.openModule("transmissionParameters__POA")

#
# Start of module "maintenanceOps"
#
__name__ = "maintenanceOps"
_0_maintenanceOps = omniORB.openModule("maintenanceOps", r"maintenanceOps.idl")
_0_maintenanceOps__POA = omniORB.openModule("maintenanceOps__POA", r"maintenanceOps.idl")


# typedef ... MaintenanceOperation_T
class MaintenanceOperation_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/maintenanceOps/MaintenanceOperation_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_maintenanceOps.MaintenanceOperation_T = MaintenanceOperation_T
_0_maintenanceOps._d_MaintenanceOperation_T  = (omniORB.tcInternal.tv_string,0)
_0_maintenanceOps._ad_MaintenanceOperation_T = (omniORB.tcInternal.tv_alias, MaintenanceOperation_T._NP_RepositoryId, "MaintenanceOperation_T", (omniORB.tcInternal.tv_string,0))
_0_maintenanceOps._tc_MaintenanceOperation_T = omniORB.tcInternal.createTypeCode(_0_maintenanceOps._ad_MaintenanceOperation_T)
omniORB.registerType(MaintenanceOperation_T._NP_RepositoryId, _0_maintenanceOps._ad_MaintenanceOperation_T, _0_maintenanceOps._tc_MaintenanceOperation_T)
del MaintenanceOperation_T

# enum MaintenanceOperationMode_T
_0_maintenanceOps.MOM_OPERATE = omniORB.EnumItem("MOM_OPERATE", 0)
_0_maintenanceOps.MOM_RELEASE = omniORB.EnumItem("MOM_RELEASE", 1)
_0_maintenanceOps.MaintenanceOperationMode_T = omniORB.Enum("IDL:mtnm.tmforum.org/maintenanceOps/MaintenanceOperationMode_T:1.0", (_0_maintenanceOps.MOM_OPERATE, _0_maintenanceOps.MOM_RELEASE,))

_0_maintenanceOps._d_MaintenanceOperationMode_T  = (omniORB.tcInternal.tv_enum, _0_maintenanceOps.MaintenanceOperationMode_T._NP_RepositoryId, "MaintenanceOperationMode_T", _0_maintenanceOps.MaintenanceOperationMode_T._items)
_0_maintenanceOps._tc_MaintenanceOperationMode_T = omniORB.tcInternal.createTypeCode(_0_maintenanceOps._d_MaintenanceOperationMode_T)
omniORB.registerType(_0_maintenanceOps.MaintenanceOperationMode_T._NP_RepositoryId, _0_maintenanceOps._d_MaintenanceOperationMode_T, _0_maintenanceOps._tc_MaintenanceOperationMode_T)

# struct CurrentMaintenanceOperation_T
_0_maintenanceOps.CurrentMaintenanceOperation_T = omniORB.newEmptyClass()
class CurrentMaintenanceOperation_T (omniORB.StructBase):
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/maintenanceOps/CurrentMaintenanceOperation_T:1.0"

    def __init__(self, tpName, maintenanceOperation, layerRate, additionalInfo):
        self.tpName = tpName
        self.maintenanceOperation = maintenanceOperation
        self.layerRate = layerRate
        self.additionalInfo = additionalInfo

_0_maintenanceOps.CurrentMaintenanceOperation_T = CurrentMaintenanceOperation_T
_0_maintenanceOps._d_CurrentMaintenanceOperation_T  = (omniORB.tcInternal.tv_struct, CurrentMaintenanceOperation_T, CurrentMaintenanceOperation_T._NP_RepositoryId, "CurrentMaintenanceOperation_T", "tpName", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], "maintenanceOperation", omniORB.typeMapping["IDL:mtnm.tmforum.org/maintenanceOps/MaintenanceOperation_T:1.0"], "layerRate", omniORB.typeMapping["IDL:mtnm.tmforum.org/transmissionParameters/LayerRate_T:1.0"], "additionalInfo", omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NVSList_T:1.0"])
_0_maintenanceOps._tc_CurrentMaintenanceOperation_T = omniORB.tcInternal.createTypeCode(_0_maintenanceOps._d_CurrentMaintenanceOperation_T)
omniORB.registerType(CurrentMaintenanceOperation_T._NP_RepositoryId, _0_maintenanceOps._d_CurrentMaintenanceOperation_T, _0_maintenanceOps._tc_CurrentMaintenanceOperation_T)
del CurrentMaintenanceOperation_T

# typedef ... CurrentMaintenanceOperationList_T
class CurrentMaintenanceOperationList_T:
    _NP_RepositoryId = "IDL:mtnm.tmforum.org/maintenanceOps/CurrentMaintenanceOperationList_T:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_maintenanceOps.CurrentMaintenanceOperationList_T = CurrentMaintenanceOperationList_T
_0_maintenanceOps._d_CurrentMaintenanceOperationList_T  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/maintenanceOps/CurrentMaintenanceOperation_T:1.0"], 0)
_0_maintenanceOps._ad_CurrentMaintenanceOperationList_T = (omniORB.tcInternal.tv_alias, CurrentMaintenanceOperationList_T._NP_RepositoryId, "CurrentMaintenanceOperationList_T", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:mtnm.tmforum.org/maintenanceOps/CurrentMaintenanceOperation_T:1.0"], 0))
_0_maintenanceOps._tc_CurrentMaintenanceOperationList_T = omniORB.tcInternal.createTypeCode(_0_maintenanceOps._ad_CurrentMaintenanceOperationList_T)
omniORB.registerType(CurrentMaintenanceOperationList_T._NP_RepositoryId, _0_maintenanceOps._ad_CurrentMaintenanceOperationList_T, _0_maintenanceOps._tc_CurrentMaintenanceOperationList_T)
del CurrentMaintenanceOperationList_T

# interface CurrentMaintenanceOperationIterator_I
_0_maintenanceOps._d_CurrentMaintenanceOperationIterator_I = (omniORB.tcInternal.tv_objref, "IDL:mtnm.tmforum.org/maintenanceOps/CurrentMaintenanceOperationIterator_I:1.0", "CurrentMaintenanceOperationIterator_I")
omniORB.typeMapping["IDL:mtnm.tmforum.org/maintenanceOps/CurrentMaintenanceOperationIterator_I:1.0"] = _0_maintenanceOps._d_CurrentMaintenanceOperationIterator_I
_0_maintenanceOps.CurrentMaintenanceOperationIterator_I = omniORB.newEmptyClass()
class CurrentMaintenanceOperationIterator_I :
    _NP_RepositoryId = _0_maintenanceOps._d_CurrentMaintenanceOperationIterator_I[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_maintenanceOps.CurrentMaintenanceOperationIterator_I = CurrentMaintenanceOperationIterator_I
_0_maintenanceOps._tc_CurrentMaintenanceOperationIterator_I = omniORB.tcInternal.createTypeCode(_0_maintenanceOps._d_CurrentMaintenanceOperationIterator_I)
omniORB.registerType(CurrentMaintenanceOperationIterator_I._NP_RepositoryId, _0_maintenanceOps._d_CurrentMaintenanceOperationIterator_I, _0_maintenanceOps._tc_CurrentMaintenanceOperationIterator_I)

# CurrentMaintenanceOperationIterator_I operations and attributes
CurrentMaintenanceOperationIterator_I._d_next_n = ((omniORB.tcInternal.tv_ulong, ), (omniORB.tcInternal.tv_boolean, omniORB.typeMapping["IDL:mtnm.tmforum.org/maintenanceOps/CurrentMaintenanceOperationList_T:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
CurrentMaintenanceOperationIterator_I._d_getLength = ((), (omniORB.tcInternal.tv_ulong, ), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
CurrentMaintenanceOperationIterator_I._d_destroy = ((), (), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})

# CurrentMaintenanceOperationIterator_I object reference
class _objref_CurrentMaintenanceOperationIterator_I (CORBA.Object):
    _NP_RepositoryId = CurrentMaintenanceOperationIterator_I._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def next_n(self, *args):
        return self._obj.invoke("next_n", _0_maintenanceOps.CurrentMaintenanceOperationIterator_I._d_next_n, args)

    def getLength(self, *args):
        return self._obj.invoke("getLength", _0_maintenanceOps.CurrentMaintenanceOperationIterator_I._d_getLength, args)

    def destroy(self, *args):
        return self._obj.invoke("destroy", _0_maintenanceOps.CurrentMaintenanceOperationIterator_I._d_destroy, args)

omniORB.registerObjref(CurrentMaintenanceOperationIterator_I._NP_RepositoryId, _objref_CurrentMaintenanceOperationIterator_I)
_0_maintenanceOps._objref_CurrentMaintenanceOperationIterator_I = _objref_CurrentMaintenanceOperationIterator_I
del CurrentMaintenanceOperationIterator_I, _objref_CurrentMaintenanceOperationIterator_I

# CurrentMaintenanceOperationIterator_I skeleton
__name__ = "maintenanceOps__POA"
class CurrentMaintenanceOperationIterator_I (PortableServer.Servant):
    _NP_RepositoryId = _0_maintenanceOps.CurrentMaintenanceOperationIterator_I._NP_RepositoryId


    _omni_op_d = {"next_n": _0_maintenanceOps.CurrentMaintenanceOperationIterator_I._d_next_n, "getLength": _0_maintenanceOps.CurrentMaintenanceOperationIterator_I._d_getLength, "destroy": _0_maintenanceOps.CurrentMaintenanceOperationIterator_I._d_destroy}

CurrentMaintenanceOperationIterator_I._omni_skeleton = CurrentMaintenanceOperationIterator_I
_0_maintenanceOps__POA.CurrentMaintenanceOperationIterator_I = CurrentMaintenanceOperationIterator_I
omniORB.registerSkeleton(CurrentMaintenanceOperationIterator_I._NP_RepositoryId, CurrentMaintenanceOperationIterator_I)
del CurrentMaintenanceOperationIterator_I
__name__ = "maintenanceOps"

# interface MaintenanceMgr_I
_0_maintenanceOps._d_MaintenanceMgr_I = (omniORB.tcInternal.tv_objref, "IDL:mtnm.tmforum.org/maintenanceOps/MaintenanceMgr_I:1.0", "MaintenanceMgr_I")
omniORB.typeMapping["IDL:mtnm.tmforum.org/maintenanceOps/MaintenanceMgr_I:1.0"] = _0_maintenanceOps._d_MaintenanceMgr_I
_0_maintenanceOps.MaintenanceMgr_I = omniORB.newEmptyClass()
class MaintenanceMgr_I (_0_common.Common_I):
    _NP_RepositoryId = _0_maintenanceOps._d_MaintenanceMgr_I[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_maintenanceOps.MaintenanceMgr_I = MaintenanceMgr_I
_0_maintenanceOps._tc_MaintenanceMgr_I = omniORB.tcInternal.createTypeCode(_0_maintenanceOps._d_MaintenanceMgr_I)
omniORB.registerType(MaintenanceMgr_I._NP_RepositoryId, _0_maintenanceOps._d_MaintenanceMgr_I, _0_maintenanceOps._tc_MaintenanceMgr_I)

# MaintenanceMgr_I operations and attributes
MaintenanceMgr_I._d_performMaintenanceOperation = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/maintenanceOps/CurrentMaintenanceOperation_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/maintenanceOps/MaintenanceOperationMode_T:1.0"]), (), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})
MaintenanceMgr_I._d_getActiveMaintenanceOperations = ((omniORB.typeMapping["IDL:mtnm.tmforum.org/globaldefs/NamingAttributes_T:1.0"], omniORB.tcInternal.tv_ulong), (omniORB.typeMapping["IDL:mtnm.tmforum.org/maintenanceOps/CurrentMaintenanceOperationList_T:1.0"], omniORB.typeMapping["IDL:mtnm.tmforum.org/maintenanceOps/CurrentMaintenanceOperationIterator_I:1.0"]), {_0_globaldefs.ProcessingFailureException._NP_RepositoryId: _0_globaldefs._d_ProcessingFailureException})

# MaintenanceMgr_I object reference
class _objref_MaintenanceMgr_I (_0_common._objref_Common_I):
    _NP_RepositoryId = MaintenanceMgr_I._NP_RepositoryId

    def __init__(self, obj):
        _0_common._objref_Common_I.__init__(self, obj)

    def performMaintenanceOperation(self, *args):
        return self._obj.invoke("performMaintenanceOperation", _0_maintenanceOps.MaintenanceMgr_I._d_performMaintenanceOperation, args)

    def getActiveMaintenanceOperations(self, *args):
        return self._obj.invoke("getActiveMaintenanceOperations", _0_maintenanceOps.MaintenanceMgr_I._d_getActiveMaintenanceOperations, args)

omniORB.registerObjref(MaintenanceMgr_I._NP_RepositoryId, _objref_MaintenanceMgr_I)
_0_maintenanceOps._objref_MaintenanceMgr_I = _objref_MaintenanceMgr_I
del MaintenanceMgr_I, _objref_MaintenanceMgr_I

# MaintenanceMgr_I skeleton
__name__ = "maintenanceOps__POA"
class MaintenanceMgr_I (_0_common__POA.Common_I):
    _NP_RepositoryId = _0_maintenanceOps.MaintenanceMgr_I._NP_RepositoryId


    _omni_op_d = {"performMaintenanceOperation": _0_maintenanceOps.MaintenanceMgr_I._d_performMaintenanceOperation, "getActiveMaintenanceOperations": _0_maintenanceOps.MaintenanceMgr_I._d_getActiveMaintenanceOperations}
    _omni_op_d.update(_0_common__POA.Common_I._omni_op_d)

MaintenanceMgr_I._omni_skeleton = MaintenanceMgr_I
_0_maintenanceOps__POA.MaintenanceMgr_I = MaintenanceMgr_I
omniORB.registerSkeleton(MaintenanceMgr_I._NP_RepositoryId, MaintenanceMgr_I)
del MaintenanceMgr_I
__name__ = "maintenanceOps"

#
# End of module "maintenanceOps"
#
__name__ = "maintenanceOps_idl"

_exported_modules = ( "maintenanceOps", )

# The end.
