# DO NOT EDIT THIS FILE!
#
# Python module callSNC generated by omniidl

import omniORB
omniORB.updateModule("callSNC")

# ** 1. Stub files contributing to this module
from corba_client.IDL import callSNC_idl

# ** 2. Sub-modules

# ** 3. End
