# DO NOT EDIT THIS FILE!
#
# Python module mLSNPP generated by omniidl

import omniORB
omniORB.updateModule("mLSNPP")

# ** 1. Stub files contributing to this module
import mLSNPP_idl

# ** 2. Sub-modules

# ** 3. End
