# DO NOT EDIT THIS FILE!
#
# Python module mtnmVersion generated by omniidl

import omniORB
omniORB.updateModule("mtnmVersion")

# ** 1. Stub files contributing to this module

# ** 2. Sub-modules

# ** 3. End
