# DO NOT EDIT THIS FILE!
#
# Python module protection generated by omniidl

import omniORB
omniORB.updateModule("protection")

# ** 1. Stub files contributing to this module
from corba_client.IDL import protection_idl

# ** 2. Sub-modules

# ** 3. End
