# DO NOT EDIT THIS FILE!
#
# Python module performance__POA generated by omniidl

import omniORB
omniORB.updateModule("performance__POA")

# ** 1. Stub files contributing to this module
import performance_idl

# ** 2. Sub-modules

# ** 3. End
