# DO NOT EDIT THIS FILE!
#
# Python module emsSession__POA generated by omniidl

import omniORB
omniORB.updateModule("emsSession__POA")

# ** 1. Stub files contributing to this module

# ** 2. Sub-modules

# ** 3. End
