# DO NOT EDIT THIS FILE!
#
# Python module DsNotifyLogAdmin__POA generated by omniidl

import omniORB
omniORB.updateModule("DsNotifyLogAdmin__POA")

# ** 1. Stub files contributing to this module
import DsNotifyLogAdmin_idl

# ** 2. Sub-modules

# ** 3. End
