# DO NOT EDIT THIS FILE!
#
# Python module aSAP__POA generated by omniidl

import omniORB
omniORB.updateModule("aSAP__POA")

# ** 1. Stub files contributing to this module
import aSAP_idl
#from corba_client.IDL
# ** 2. Sub-modules

# ** 3. End
