# DO NOT EDIT THIS FILE!
#
# Python module transmissionDescriptor generated by omniidl

import omniORB
omniORB.updateModule("transmissionDescriptor")

# ** 1. Stub files contributing to this module
import transmissionDescriptor_idl

# ** 2. Sub-modules

# ** 3. End
