# DO NOT EDIT THIS FILE!
#
# Python module trafficDescriptor__POA generated by omniidl

import omniORB
omniORB.updateModule("trafficDescriptor__POA")

# ** 1. Stub files contributing to this module
from corba_client.IDL import trafficDescriptor_idl

# ** 2. Sub-modules

# ** 3. End
