# DO NOT EDIT THIS FILE!
#
# Python module mLSNPP__POA generated by omniidl

import omniORB
omniORB.updateModule("mLSNPP__POA")

# ** 1. Stub files contributing to this module
from corba_client.IDL import mLSNPP_idl

# ** 2. Sub-modules

# ** 3. End
