# DO NOT EDIT THIS FILE!
#
# Python module maintenanceOps generated by omniidl

import omniORB
omniORB.updateModule("maintenanceOps")

# ** 1. Stub files contributing to this module
import maintenanceOps_idl

# ** 2. Sub-modules

# ** 3. End
